# Generated by Django 6.0.3 on 2026-04-12 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='is_submitted',
        ),
    ]
