# Generated by Django 6.0.3 on 2026-04-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_remove_grade_is_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
